### PR TITLE
Enhancement: make the zscript compatible for older version of zbrush

### PR DESCRIPTION
**Pull request by moonyuet**
##Changelog Description
Make the zscript menu compatible with the zbrush version prior to Maxon's acquirement.

##Testing Notes
Pixelogic Zbrush
1. Launch Zbrush via AYON launcher
2. Find `ayon_zbrush_menu.txt` in `{ayon-zbrush-repo}/api/zscripts`
3. Move the scripts into `C:\Program Files\Pixologic\ZBrush 2019.1 FL\ZStartup\ZPlugs64`
4. Load the script in zscript menu in the launched ZBrush
5. Everything should be loaded as expected

Maxon Zbrush
1.  Launch Zbrush via AYON launcher
2. The menu should be loaded as expected

### CODE REVIEW

**Comment by LiborBatek** [comment]
@moonyuet can we close it? or? I guess you tested on your side and that might be enough for now??
@BigRoy opinion on that? as I guess its not uber important as its a kind of edge case anyway, or if any issues later on...potentionally could be fixed then

**Comment by moonyuet** [comment]
> @moonyuet can we close it? or? I guess you tested on your side and that might be enough for now?? @BigRoy opinion on that? as I guess its not uber important as its a kind of edge case anyway, or if any issues later on...potentionally could be fixed then

this branch includes the menu is for the elder version of the zbrush before Maxon acquiring the software . Maybe we can keep the branch while closing it.(Just in case if anyone has really old version and we can still know how to deal with it)

**Comment by BigRoy** [comment]
Check in with clients using Zbrush integration - are they all on Maxon versions? If so, close. If not, and clients need this - I'd say test it with their systems to confirm and then go. 🚀 

If not needed, close and the closed PR will be a trace left if it ever comes up again.

Preferably we can start dropping the legacy support of course.

**Comment by LiborBatek** [comment]
@BigRoy @moonyuet its confirmed and tested > working ok. Can be merged I guess now

**Comment by moonyuet** [comment]
Closed as it is only for the pixelogic zbrush. We just left the branch here and once if there is any user from pixelogic, it can be taken as reference.

**Pull request closed without merging**
