### PR TITLE
Chore: Update and fix client addon

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Description
Use `ayon_core.addon` import instead of `ayon_core.modules`. And don't use runtime dependencies in addon definition, rather import it when needed.

### CODE REVIEW

**Comment by moonyuet** [comment]
I can launch the tools but the launching is super slow.

https://github.com/user-attachments/assets/5f681ed1-6bc3-416c-9259-c5cf40676de4


And I find out that so many terminal
image

**Comment by iLLiCiTiT** [comment]
Is that related to this PR? I just changed imports and moved functions around, didn't change what is launched and how.

**Comment by moonyuet** [comment]
> Is that related to this PR? I just changed imports and moved functions around, didn't change what is launched and how.

But I tested it with the develop with the use of` ayon_core.addon` import instead of `ayon_core.modules`, it works like as usual.

**Comment by iLLiCiTiT** [comment]
Reverted changes related to `run_with_zscript` from this PR.

**Comment by BigRoy** [comment]
> And don't use runtime dependencies in addon definition, rather import it when needed.

Is this still in the PR?

**Review by moonyuet — APPROVED** [review]

**Pull request merged**
